#!/bin/bash

TS="./ts/*.ts"

for f in $TS
do
	filename=$(basename "$f")
	extension="${filename##*.}"
	filename="${filename%.*}"
	echo "--------------------------";
	echo "Releasing QM file for $filename language";
	lrelease $f -qm ./qm/$filename.qm
done
